project:
  type: book

book:
  title: "CASA0023 - Personal Diary"
  chapters:
  - title: "Week 1"
    file: Week_1.qmd
  - title: "Week 2"
    file: Week_2.qmd
  - title: "Week 3"
    file: Week_3.qmd
  - title: "Week 4"
    file: Week_4.qmd
  - title: "Week 5"
    file: Week_5.qmd
  - title: "References"
    file: references.qmd