project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 - Personal Diary"
  chapters:
    - index.qmd
    - Week 1.qmd
    - Week 2.qmd
    - Week 3.qmd
    - Week 4.qmd
    - Week 5.qmd
    - references.qmd
