# \-\--

title: "About Me"

\-\--

Hello to all. I am Ana :)

First of all, I am a proud Colombian woman, very interested in understanding socio-cultural, economic and environmental behaviors around me, and committed to improving livelihoods and generating sustainable conditions for people and communities around the world.

I studied anthropology for my undergrad and later finished an MSc in Sustainable Development, currently I am studying an MSc in Social and Geographic Data Science. I have more than 8 years of experience working in rural development in Colombia, analyzing and developing different economic activities that contribute to both cultural and environmental conservation; as well as coordinating resources and efforts with regional governments, NGO's and the environmental sector for a more contextualized and adequate regional planning.

My expectation with this masters is to acquire as many tools and skills in social and environmental data collection and analysis, that will permit me to continue designing, implementing and evaluating development projects and programs. Regarding this specific course, I am confident that a better understanding of how to generate and analyse various types of remote sensing data is a great compliment on diagnosing environmental and social problematics and then designing plausible solutions.
